name: adminer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'adminer/**'

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Login to Aliyun
        uses: docker/login-action@v1.10.0
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          version: latest
      - name: Build
        id: build
        run: bash adminer/build.sh
