name: xray

on:
  workflow_dispatch:
  push:
    paths:
      - 'xray/**'
      - '.github/workflows/xray.yml'

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
      - name: Login to Aliyun
        uses: docker/login-action@v1.9.0
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.1.0
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          version: latest
      - name: Build
        id: build
        run: bash xray/build.sh
